image: node:12

stages:
    - test
    - deploy

test:
    stage: test
    script:
        - apk add npm
        - npm install --registry=https://registry.npm.taobao.org
        - npm run build

deploy-staging:
    stage: deploy
    only: staging
    script:
        - curl -X POST -F token=fb8d1f500ea2ef085afbfb2b69a183 -F ref=staging https://git.uestc.cn/api/v4/projects/553/trigger/pipeline

deploy-production:
    stage: deploy
    only: master
    script:
        - curl -X POST -F token=fb8d1f500ea2ef085afbfb2b69a183 -F ref=master https://git.uestc.cn/api/v4/projects/553/trigger/pipeline
