image: registry.stuhome.com/devops/dockerepo/docker:1.0.2

stages:
    - build
    - deploy

build-staging-image:
    stage: build

    script:
        - star_ci_build staging 2019Recruitment-fe

    only:
        - staging

    allow_failure: false

deploy-staging:
    stage: deploy

    script:
        - star_ci_deploy staging 2019Recruitment-fe

    only:
        - staging

    environment:
        name: staging
    tags:
        - staging

    allow_failure: false
    when: on_success


build-production-image:
    stage: build

    script:
        - star_ci_build production 2019Recruitment-fe

    allow_failure: false
    only:
        - master

deploy-production:
    stage: deploy

    script:
        - star_ci_deploy production 2019Recruitment-fe

    only:
        - master

    environment:
        name: production
    tags:
        - production

    allow_failure: false
    when: manual
